### ISSUE TITLE
Test Error

### ISSUE THREAD

**Issue by ostix360** [juvi21/CoPE-cuda#1]
After cloning and installing via pip install -e . 
I run the tests via pytest tests and I got import errors for flip and cumsum
No module named  'cumsum' and same for flip

I run it on  a 
venv
Python 3.11
WSL2

**Comment by juvi21** [comment]
Could you please provide a more specific error message, including the output of the `pip install -e . ` command? 
To be honest, I haven't tried this on WSL. It seems like the CUDA kernels are not compiling. Please ensure that you have CUDA installed.

**Comment by ostix360** [comment]
output of pip install
Obtaining file:///mnt/o/optimize_lm/CoPE-cuda
  Preparing metadata (setup.py) ... done
Installing collected packages: flipcumsums
  Running setup.py develop for flipcumsums
Successfully installed flipcumsums-0.0.0

And my cuda is installed.

The libs are compiled but at the root of the project:
 cumsum.cpython-311-x86_64-linux-gnu.so*
flip.cpython-311-x86_64-linux-gnu.so*
flipcumsum.cpython-311-x86_64-linux-gnu.so*
flipcumsums.egg-info/

I don't see them in the site-package directory (where I guess the libs should be)

**Comment by juvi21** [comment]
which pip version your running? Also maybe your setuptools version.

**Comment by ostix360** [comment]
I'm running the last version of pip 
and I just update the version of setuptools to the last one but I was running the setuptools to 68.2.0

**Comment by ostix360** [comment]
I had to install with a cleaner conda env
Thanks for you answers
